### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by samip5** [bruvv/docker-ram-usage-checker#1]
Why are you using PIP directly from the script? 

You should be using a requirements file.

`pip freeze > requirements.txt`

**Comment by bruvv** [comment]
because I am running this in a python3-slim docker (with no docker file) so this is the easiest sollution that I know off ;)

**Comment by samip5** [comment]
Alright,  could you then maybe share how exactly are you running the script?  :)

**Comment by bruvv** [comment]
I am running it in Synology Docker, so I create an container and than in the in the last tab there is an option to change the running command when the docker starts. I change that to:
![image](https://user-images.githubusercontent.com/3063928/52045583-1eba2e80-2545-11e9-9596-7125bead5721.png)
And ofc I added the volume /stats/ that links to where the files are located on my disk

but I added the requirments file if people really need it. Now it is just run 1 file and than that should take care of everything :)
